In [1]:
import numpy as np
from scipy.linalg import svdvals
from numpy import linalg as LA

In [19]:
M = np.asarray([[0,0,0,0,1,1,1,1],
                [1,1,1,1,0,0,0,0,],
                [0,0,1,1,0,0,1,1],
                [1,1,0,0,1,1,0,0],
                [0,1,0,1,0,1,0,1],
                [1,0,1,0,1,0,1,0],
                [0,1,0,1,0,1,0,1],
                [1,0,1,0,1,0,1,0]])

In [3]:
print(M.shape)

(8, 8)


In [4]:
U, S, Vh = np.linalg.svd(M, full_matrices=True)

In [5]:
U.shape, S.shape, Vh.shape

((8, 8), (8,), (8, 8))

In [6]:
print(S)

S_sub = S[0:4]
print(S_sub)
S_sub_diag = np.diag(S_sub)

[4.00000000e+00 2.82842712e+00 2.00000000e+00 2.00000000e+00
 2.92628160e-16 1.11228628e-16 3.32603860e-32 0.00000000e+00]
[4.         2.82842712 2.         2.        ]


In [7]:
U_sub = U[:, 0:4]
print(U_sub)

[[-3.53553391e-01 -2.22044605e-16 -5.00000000e-01 -5.00000000e-01]
 [-3.53553391e-01  4.99600361e-16  5.00000000e-01  5.00000000e-01]
 [-3.53553391e-01 -2.35922393e-16 -5.00000000e-01  5.00000000e-01]
 [-3.53553391e-01  2.77555756e-16  5.00000000e-01 -5.00000000e-01]
 [-3.53553391e-01  5.00000000e-01 -2.77555756e-16 -8.32667268e-17]
 [-3.53553391e-01 -5.00000000e-01  1.94289029e-16  5.55111512e-17]
 [-3.53553391e-01  5.00000000e-01 -2.77555756e-16  2.77555756e-17]
 [-3.53553391e-01 -5.00000000e-01  1.94289029e-16  5.55111512e-17]]


In [8]:
V_sub = Vh[0:4, :]
print(V_sub)
V_sub.shape

[[-3.53553391e-01 -3.53553391e-01 -3.53553391e-01 -3.53553391e-01
  -3.53553391e-01 -3.53553391e-01 -3.53553391e-01 -3.53553391e-01]
 [-3.53553391e-01  3.53553391e-01 -3.53553391e-01  3.53553391e-01
  -3.53553391e-01  3.53553391e-01 -3.53553391e-01  3.53553391e-01]
 [ 5.00000000e-01  5.00000000e-01  5.55111512e-17  0.00000000e+00
   0.00000000e+00 -2.77555756e-16 -5.00000000e-01 -5.00000000e-01]
 [ 2.15416017e-16 -1.88480027e-16  5.00000000e-01  5.00000000e-01
  -5.00000000e-01 -5.00000000e-01 -2.69750747e-17  1.11022302e-16]]


(4, 8)

In [9]:
U_sub.shape

(8, 4)

In [10]:
S_sub.shape

(4,)

In [11]:
S.shape

(8,)

In [12]:
np.around(U_sub @ S_sub_diag @ V_sub, decimals=2, out=None)

array([[-0., -0.,  0., -0.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1., -0., -0., -0.,  0.],
       [ 0., -0.,  1.,  1.,  0., -0.,  1.,  1.],
       [ 1.,  1.,  0.,  0.,  1.,  1., -0., -0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1., -0.,  1., -0.,  1.,  0.,  1., -0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1., -0.,  1., -0.,  1.,  0.,  1., -0.]])

In [61]:
np.around(U_sub, decimals=2, out=None)

array([[-0.35, -0.  , -0.5 , -0.5 ],
       [-0.35,  0.  ,  0.5 ,  0.5 ],
       [-0.35, -0.  , -0.5 ,  0.5 ],
       [-0.35,  0.  ,  0.5 , -0.5 ],
       [-0.35,  0.5 , -0.  , -0.  ],
       [-0.35, -0.5 ,  0.  ,  0.  ],
       [-0.35,  0.5 , -0.  ,  0.  ],
       [-0.35, -0.5 ,  0.  ,  0.  ]])

In [62]:
np.around(S_sub_diag, decimals=2, out=None)

array([[4.  , 0.  , 0.  , 0.  ],
       [0.  , 2.83, 0.  , 0.  ],
       [0.  , 0.  , 2.  , 0.  ],
       [0.  , 0.  , 0.  , 2.  ]])

In [66]:
np.around(V_sub, decimals=2, out=None)

array([[-0.35, -0.35, -0.35, -0.35, -0.35, -0.35, -0.35, -0.35],
       [-0.35,  0.35, -0.35,  0.35, -0.35,  0.35, -0.35,  0.35],
       [ 0.5 ,  0.5 ,  0.  ,  0.  ,  0.  , -0.  , -0.5 , -0.5 ],
       [ 0.  , -0.  ,  0.5 ,  0.5 , -0.5 , -0.5 , -0.  ,  0.  ]])

In [18]:
np.linalg.solve(V_sub, np.asarray([0,0,0,0,1,1,1,1]))

LinAlgError: Last 2 dimensions of the array must be square

In [ ]:
np.linalg.solve()

In [64]:
def bmatrix(a):
    """Returns a LaTeX bmatrix

    :a: numpy array
    :returns: LaTeX bmatrix as a string
    """
    if len(a.shape) > 2:
        raise ValueError('bmatrix can at most display two dimensions')
    lines = str(a).replace('[', '').replace(']', '').splitlines()
    rv = [r'\begin{bmatrix}']
    rv += ['  ' + ' & '.join(l.split()) + r'\\' for l in lines]
    rv +=  [r'\end{bmatrix}']
    return '\n'.join(rv)


In [65]:
bmatrix(np.around(U_sub, decimals=2, out=None))

'\\begin{bmatrix}\n  -0.35 & -0. & -0.5 & -0.5\\\\\n  -0.35 & 0. & 0.5 & 0.5\\\\\n  -0.35 & -0. & -0.5 & 0.5\\\\\n  -0.35 & 0. & 0.5 & -0.5\\\\\n  -0.35 & 0.5 & -0. & -0.\\\\\n  -0.35 & -0.5 & 0. & 0.\\\\\n  -0.35 & 0.5 & -0. & 0.\\\\\n  -0.35 & -0.5 & 0. & 0.\\\\\n\\end{bmatrix}'